# Generated by Django 4.2.3 on 2023-10-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "Id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Идентификатор"
                    ),
                ),
                (
                    "PurchaseOrder",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Заказ на закупку",
                    ),
                ),
                (
                    "RegistryNumber",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Реестровый номер",
                    ),
                ),
                (
                    "ProcurementMethod",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Метод закупки",
                    ),
                ),
                (
                    "PurchaseName",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Наименование закупки",
                    ),
                ),
                (
                    "AuctionSubject",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Предмет аукциона",
                    ),
                ),
                (
                    "PurchaseIdentificationCode",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Код идентификации закупки",
                    ),
                ),
                (
                    "LotNumber",
                    models.IntegerField(
                        default="Нет данных", null=True, verbose_name="Номер лота"
                    ),
                ),
                (
                    "LotName",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Наименование лота",
                    ),
                ),
                (
                    "InitialMaxContractPrice",
                    models.FloatField(
                        blank=True,
                        default="Нет данных",
                        null=True,
                        verbose_name="Начальная максимальная цена контракта",
                    ),
                ),
                (
                    "Currency",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "InitialMaxContractPriceInCurrency",
                    models.FloatField(
                        blank=True,
                        default="Нет данных",
                        null=True,
                        verbose_name="Начальная максимальная цена контракта в валюте",
                    ),
                ),
                (
                    "ContractCurrency",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Валюта контракта",
                    ),
                ),
                (
                    "OKDPClassification",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Классификация ОКДП",
                    ),
                ),
                (
                    "OKPDClassification",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Классификация ОКПД",
                    ),
                ),
                (
                    "OKPD2Classification",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Классификация ОКПД2",
                    ),
                ),
                (
                    "PositionCode",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Код позиции",
                    ),
                ),
                (
                    "CustomerName",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Наименование заказчика",
                    ),
                ),
                (
                    "ProcurementOrganization",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Организация закупки",
                    ),
                ),
                (
                    "PlacementDate",
                    models.DateField(
                        blank=True,
                        default="Нет данных",
                        null=True,
                        verbose_name="Дата размещения",
                    ),
                ),
                (
                    "UpdateDate",
                    models.DateField(
                        blank=True,
                        default="Нет данных",
                        null=True,
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "ProcurementStage",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Этап закупки",
                    ),
                ),
                (
                    "ProcurementFeatures",
                    models.CharField(
                        blank=True,
                        default="Нет данных",
                        max_length=255,
                        null=True,
                        verbose_name="Особенности закупки",
                    ),
                ),
                (
                    "ApplicationStartDate",
                    models.DateField(
                        blank=True,
                        default="Нет данных",
                        null=True,
                        verbose_name="Дата начала заявки",
                    ),
                ),
                (
                    "ApplicationEndDate",
                    models.DateField(
                        blank=True,
                        default="Нет данных",
                        null=True,
                        verbose_name="Дата окончания заявки",
                    ),
                ),
                (
                    "AuctionDate",
                    models.DateField(
                        blank=True,
                        default="Нет данных",
                        null=True,
                        verbose_name="Дата аукциона",
                    ),
                ),
                (
                    "QueryCount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество запросов"
                    ),
                ),
                (
                    "ResponseCount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество ответов"
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "AveragePrice",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Среднее значение цены"
                    ),
                ),
                (
                    "MinPrice",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Минимальная цена"
                    ),
                ),
                (
                    "MaxPrice",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Максимальная цена"
                    ),
                ),
                (
                    "StandardDeviation",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Среднее квадратичное отклонение",
                    ),
                ),
                (
                    "CoefficientOfVariation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Коэффициент вариации"
                    ),
                ),
                (
                    "NMCKMarket",
                    models.FloatField(
                        blank=True, null=True, verbose_name="НМЦК рыночная"
                    ),
                ),
                (
                    "FinancingLimit",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Лимит финансирования"
                    ),
                ),
            ],
        ),
    ]
